# Generated by Django 3.0.8 on 2020-07-25 17:26

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='trait_eyes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='trait_eyes_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='player',
            name='trait_hair',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='trait_hair_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='player',
            name='trait_skin',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='trait_skin_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.PlayerClass'),
        ),
    ]
