# Generated by Django 3.0.8 on 2020-07-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200728_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteminstance',
            old_name='item_id',
            new_name='item',
        ),
    ]
