# Generated by Django 3.0.8 on 2020-07-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200728_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='extra_slot',
            field=models.BooleanField(default=False),
        ),
    ]
