# Generated by Django 3.0.8 on 2020-07-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_iteminstance_extra_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='base_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='diff_modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questinstance',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questinstance',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questinstance',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1),
        ),
        migrations.AddField(
            model_name='questinstance',
            name='players',
            field=models.ManyToManyField(to='API.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='quest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='quest',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='number',
        ),
    ]
