# Generated by Django 3.0.8 on 2020-07-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200728_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='map_id',
            field=models.IntegerField(default=0),
        ),
    ]
