# Generated by Django 3.0.8 on 2020-07-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(to='API.Skill'),
        ),
    ]
