# Generated by Django 3.0.8 on 2020-07-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_player_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='dmg_type',
        ),
    ]
