# Generated by Django 3.0.8 on 2020-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20200802_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='no_hat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='wpn_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Sword'), (2, 'Dagger'), (3, 'Bow'), (4, 'Spear'), (5, 'Staff'), (6, 'Book')], default=0),
        ),
    ]
