# Generated by Django 3.0.8 on 2020-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20200803_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='item',
            name='stats',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
