# Generated by Django 3.0.8 on 2020-08-08 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_task_taskinstance_taskreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
