# Generated by Django 3.0.8 on 2020-08-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_taskinstance_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
