# Generated by Django 3.0.8 on 2020-08-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_auto_20200807_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Player'),
        ),
    ]
