# Generated by Django 3.0.8 on 2020-08-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_auto_20200808_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
