# Generated by Django 3.0.8 on 2020-08-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_score_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='diamonds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
