# Generated by Django 3.0.8 on 2020-08-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_semester_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.Subject'),
            preserve_default=False,
        ),
    ]
