# Generated by Django 3.0.8 on 2020-08-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_auto_20200810_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
