# Generated by Django 3.0.8 on 2020-08-11 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_player_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 11, 33, 30, 822732)),
        ),
    ]
