# Generated by Django 3.0.8 on 2020-08-11 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_player_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
