# Generated by Django 3.0.8 on 2020-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_taskinstance_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
    ]
