# Generated by Django 3.0.8 on 2020-08-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_auto_20200812_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='...', max_length=200),
            preserve_default=False,
        ),
    ]
