# Generated by Django 3.0.8 on 2020-08-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0031_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='job_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.PlayerClass'),
        ),
        migrations.AddField(
            model_name='skill',
            name='level_req',
            field=models.IntegerField(default=1),
        ),
    ]
