# Generated by Django 3.0.8 on 2021-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_auto_20200813_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='range',
            field=models.CharField(max_length=90),
        ),
    ]
